Processes:
  zerogw:
    executable-path: /usr/bin/zerogw
    arguments:
    - zerogw
    - --config=config/zerogw.yaml
  python:
    executable-path: /usr/bin/python
    arguments:
    - python
    - -m
    - crowdpower
