bossrun:
  failfast: yes

Processes:
  zerogw:
    executable-path: /usr/bin/zerogw
    arguments:
    - zerogw
    - --config=config/zerogw.yaml
  python:
    executable-path: /usr/bin/python
    environ:
      PYTHONPATH: trafaret
    arguments:
    - python
    - -m
    - crowdpower
  redis:
    executable-path: /usr/bin/redis-server
    arguments:
    - redis-server
    - config/redis.conf
